### ISSUE TITLE
"mobilenetv1-w4a4.bit" Not Found

### ISSUE THREAD

**Issue by Wo-Ki** [Xilinx/finn-examples#1]
Hi, When I run **2_imagenet_with_mobilenet_v1.ipynb**, line 2:
`accel = models.mobilenetv1_w4a4_imagenet()`
Error like:
`KeyError: 'finn_examples/bitfiles/Pynq-Z2/mobilenetv1-w4a4.bit'`
I found:
![image](https://user-images.githubusercontent.com/29698317/103115601-3a310400-469e-11eb-95fe-516aa2ffa18a.png)
So, can you update this model? Thank you very much.

**Comment by maltanar** [comment]
Which board are you trying to run this on? The MobileNet-v1 is currently only supported on the Alveo U250.

**Comment by Wo-Ki** [comment]
> Which board are you trying to run this on? The MobileNet-v1 is currently only supported on the Alveo U250.

Oh，I see.My board is pynq-z2. I hope you can update it as fast as you can, I want to try this. Thank you.

**Comment by maltanar** [comment]
Unfortunately the FPGA on the PYNQ-Z2 is too small to deploy MobileNet-v1 as a dataflow-style architecture so there are no plans to do this. We'll be releasing MobileNet-v1 for the ZCU104 but not for anything smaller.

Depending on your use case https://github.com/Xilinx/DPU-PYNQ may be of interest.
