### ISSUE TITLE
2_imagenet_with_cnns.ipynb stuck

### ISSUE THREAD

**Issue by laochonlam** [Xilinx/finn-examples#28]
Hi FINN community,

When I ran `2_imagenet_with_cnns.ipynb` I found out that it stucked when I set batch size other than 1. The program will be hang on `obuf_normal = accel.execute(ibuf_normal)`. 

<img width="1713" alt="image" src="https://user-images.githubusercontent.com/14297310/145700431-bf83e59e-7e70-4c5d-a15e-4ba1d9899ab4.png">

Do you have any clue for this?

Thanks,
Lam

**Comment by mmrahorovic** [comment]
Hi @laochonlam, thank you for your post!
Unfortunately, I have not encountered this issue before. However, I would advise to give the latest [FINN-examples release](https://github.com/Xilinx/finn-examples/tree/v0.0.6) a try. Please let me know if you still observe the same problem.

**Comment by auphelia** [comment]
Closing this issue for now, please feel free to re-open if your problem isn't solved.
