### ISSUE TITLE
How to I run an example on U250 

### ISSUE THREAD

**Issue by saitej25** [Xilinx/finn-examples#3]
Hello, 
I've created an nimbix instance with U250 card and 2018_3 firmware. How can I run an sample ?

**Comment by maltanar** [comment]
Hi Sai, the instructions on the README should suffice. Summarizing for Alveo:

1. Creating and activating a PYNQ virtual environment a la https://pynq.readthedocs.io/en/v2.6.1/getting_started/alveo_getting_started.html?highlight=alveo#install-conda
2. Ensuring setuptools up to date `python3 -m pip install --upgrade pip setuptools`
3. `pip3 install finn-examples` to install
4. `pynq get-notebooks --from-package finn-examples -p .` to get the notebooks and run the notebooks with Jupyter

I've not had a chance to test on Nimbix instances, would be good to know if everything works smoothly.
