### ISSUE TITLE
How to dump the weights of the pretrained model

### ISSUE THREAD

**Issue by YukeWang96** [Xilinx/finn-examples#4]
**Hi, All**

I want to dump the weights of the pre-trained model for those three examples. Is it possible to get these weights without connecting the PYNQ-board? (i.e., stand-alone execution on host CPU only)

**Thanks!**

**Comment by maltanar** [comment]
Hi YukeWang96, this is indeed possible, and at several different stages depending on what you'd like to do. 

1) If you want to access the weights at PyTorch level (before the FINN compiler optimizes anything) you can do this by downloading the appropriate checkpoints from https://github.com/Xilinx/brevitas/tags -- e.g. https://github.com/Xilinx/brevitas/releases/tag/bnn_pynq-r0 will have the PyTorch state_dict checkpoints for all the BNN-PYNQ network examples.

2) Same as above but exported to ONNX: see e.g. https://github.com/Xilinx/finn-examples/releases/download/v0.0.1a/onnx-models-bnn-pynq.zip

3) Further down the compilation flow (e.g. after streamlining and conversion to HLS): If you follow the instructions under https://github.com/Xilinx/finn-examples/tree/main/build these will produce an `intermediate_models/` folder under the outputs, which will contain an ONNX file for the model at various steps.
