### ISSUE TITLE
Update FINN version in `get_finn.sh`

### ISSUE THREAD

**Issue by zzzDavid** [Xilinx/finn-examples#43]
Hi, 
It seems that the current `get_finn.sh` script uses an older commit:
https://github.com/Xilinx/finn-examples/blob/7123fa53b73fcba0f80be009de2e83e0d48995f0/build/get-finn.sh#L30-L33

This commit point has this dependency issue where importing finn can cause:
```
from sigtools import _signatures, _util File "/opt/conda/lib/python3.8/site-packages/sigtools/_signatures.py", line 83 , in <module> @attr.define(eq=False)
AttributeError: module 'attr' has no attribute 'define'
```
I found that the fix is added by:
https://github.com/Xilinx/finn/pull/644

Updating to the latest commits in finn fixed this issue. I think it would be good to update the `get_finn.sh` commit point.

**Comment by mmrahorovic** [comment]
Hi @zzzDavid !

Great catch. The v0.0.6 FINN-examples release points to the latest FINN release (v0.9). Please give it a try, this should resolve your issue as well.
If you're running into any other issues, please let me know!
