### ISSUE TITLE
0_mnist_with_fc_networks.ipynb fails on downloading MNIST dataset

### ISSUE THREAD

**Issue by chhait07** [Xilinx/finn-examples#9]
Hi,
the dataset can't be downloaded anymore. It should be downloaded from http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz but this website doesn't exist anymore.

Is there a way for me to easily getting around this problem so that I can complete the notebook?

**Comment by maltanar** [comment]
Hi chhait07, Yann LeCun's website is down quite often nowadays. You can download the same files from e.g. https://github.com/fgnt/mnist and put the downloaded files under `/tmp` by default to skip the download.

**Comment by chhait07** [comment]
Ok, thank you
